import { spawn } from 'child_process'
import { readFile, writeFile, readdir, stat } from 'fs/promises'
import { join } from 'path'
import { getProjectConfig } from './projectConfigService'
import { safeCommand, needsShell } from './commandResolver'
import { getWorkspaceRoot } from './fsService'
import { isAllowedCommand, isBareCommand, hostCppOrNull } from '../../shared/security'

/**
 * clangd is built on clang, but the projects Cortex compiles use whatever
 * toolchain the user installed (MSYS2 g++, a cross-compiler, ...). Left alone,
 * clang cannot find <iostream> or match the build's -std, so every file lights
 * up with false errors and completion returns nothing.
 *
 * This bridges the two: it asks the project's own compiler where its system
 * headers live and what target it builds for, then writes a `.clangd` config so
 * clangd analyses code exactly the way the build does. The -std is scoped by
 * file extension because a C++ standard flag is a hard error on a C file, and
 * one clangd serves both.
 *
 * A user's own `.clangd` is never touched; a Cortex-authored one is refreshed
 * when the toolchain changes.
 */

export const MARKER = '# Generated by Cortex'

export interface Toolchain {
  target: string | null
  includes: string[]
}

/** Parse the include search paths and target triple out of a GCC/Clang `-v`
 * report. Pure, so the format assumptions are unit-tested. */
export function parseDriverOutput(text: string): Toolchain {
  const block = text.match(/#include <\.\.\.> search starts here:\r?\n([\s\S]*?)\r?\nEnd of search list\./)
  const includes = block
    ? block[1]
        .split('\n')
        .map((l) => l.trim())
        // Drop empties and Apple Clang's framework lines (" /path (framework
        // directory)"), which are not valid -isystem paths.
        .filter((l) => l && !l.endsWith('(framework directory)'))
    : []
  const target = text.match(/^Target:\s*(\S+)/m)?.[1] ?? null
  return { target, includes }
}

// Keyed by compiler command; a driver's headers do not move between opens. Holds
// the in-flight promise so concurrent opens share one probe.
const toolchainCache = new Map<string, Promise<Toolchain>>()

/**
 * Ask a GCC/Clang-family driver for its system include paths and target triple.
 * Async (never spawnSync) so an up-to-8s probe cannot freeze the main-process
 * event loop.
 */
function deriveToolchain(compiler: string): Promise<Toolchain> {
  const cached = toolchainCache.get(compiler)
  if (cached) return cached
  const probe = new Promise<Toolchain>((resolve) => {
    const empty = { target: null, includes: [] }
    let out = ''
    let settled = false
    const done = (tc: Toolchain): void => {
      if (!settled) {
        settled = true
        resolve(tc)
      }
    }
    let cp: ReturnType<typeof spawn>
    try {
      // `-E -xc++ -v -` makes the driver print its search paths and target
      // without compiling; diagnostics land on stderr.
      // PATH-resolved like every other spawn, so the probe cannot pick up a
      // compiler-shaped file from whatever cwd this process happens to hold.
      const bin = safeCommand(compiler, getWorkspaceRoot())
      if (!bin) return resolve({ target: '', includes: [] })
      cp = spawn(bin, ['-E', '-xc++', '-v', '-'], { windowsHide: true, shell: needsShell(bin) })
    // Decode UTF-8 across chunk boundaries (see runnerService).
    cp.stdout?.setEncoding('utf8')
    cp.stderr?.setEncoding('utf8')
    } catch {
      return done(empty)
    }
    const timer = setTimeout(() => {
      try {
        cp.kill()
      } catch {
        /* already gone */
      }
      done(empty)
    }, 8000)
    cp.on('error', () => {
      clearTimeout(timer)
      done(empty)
    })
    cp.stdout?.on('data', (d: Buffer) => (out += d.toString()))
    cp.stderr?.on('data', (d: Buffer) => (out += d.toString()))
    cp.on('close', () => {
      clearTimeout(timer)
      done(parseDriverOutput(out))
    })
    cp.stdin?.on('error', () => {})
    cp.stdin?.end() // the driver reads stdin ("-"); close it so it does not hang
  })
  toolchainCache.set(compiler, probe)
  // Do not cache a failed probe: a transient failure should retry on next open.
  void probe.then((tc) => {
    if (tc.includes.length === 0) toolchainCache.delete(compiler)
  })
  return probe
}

export function buildClangdConfig(
  tc: Toolchain,
  cppStd: string,
  cStd = 'c17',
  projectIncludes: string[] = [],
  depIncludes: string[] = []
): string {
  // -Wunused-variable/-Wunused-function (an unused local, a defined-but-never-
  // called function, an unused enum member) are gated behind -Wall in
  // clang/gcc; without it clangd's diagnostics stay quiet about dead code even
  // though the compile itself would warn. This is the same baseline VS
  // Code's C/C++ extension and CLion both ship with by default.
  const global: string[] = ['-Wall', '-Wextra']
  if (tc.target) global.push(`--target=${tc.target}`)
  for (const dir of tc.includes) {
    // Two argv tokens: clang takes the path as the argument after -isystem.
    global.push('-isystem', dir)
  }
  // The project's own headers as -I (warnings on: this is the user's code).
  // Without these, clangd cannot resolve a project header and every symbol it
  // declares is unknown, so completion and go-to-definition go dead across the
  // project's own modules.
  for (const dir of projectIncludes) global.push('-I', dir)
  // Third-party library headers (.pio/libdeps, lib/*) as -isystem: this is how
  // clangd finds a library header like ESP32Servo.h so member completion and
  // hover work on the classes it declares, while -isystem keeps the library's
  // own internal warnings out of the user's diagnostics. It is not a full
  // compile database (that needs the vendor toolchain), so a library that
  // transitively needs core headers clangd cannot find still degrades to the
  // curated library dictionary rather than resolving fully.
  for (const dir of depIncludes) global.push('-isystem', dir)
  const list = (flags: string[]): string => flags.map((f) => `    - ${JSON.stringify(f)}`).join('\n')
  // Multi-document YAML: a global fragment, then -std scoped by file kind so the
  // C++ standard never reaches a .c file (which clang rejects outright). The C++
  // extensions mirror CPP_EXT/langForFile in shared/lsp.ts; `c[+][+]` matches a
  // literal .c++ file without needing a backslash-escaped + inside the YAML.
  return [
    MARKER,
    '# Points clangd (code intelligence) at your build toolchain so IntelliSense',
    '# matches your compiler. Machine-specific (absolute paths): do not commit.',
    '# Safe to edit or delete; Cortex refreshes this file only while it owns it',
    '# (this header present) and the toolchain changes.',
    'CompileFlags:',
    '  Add:',
    list(global),
    '---',
    'If:',
    '  PathMatch: [".*\\\\.(cpp|cxx|cc|c[+][+]|hpp|hxx|hh|h)"]',
    'CompileFlags:',
    '  Add:',
    list([`-std=${cppStd}`]),
    '---',
    'If:',
    '  PathMatch: [".*\\\\.c"]',
    'CompileFlags:',
    '  Add:',
    list([`-std=${cStd}`]),
    ''
  ].join('\n')
}

// A library commonly puts its headers either at the package root or in a src/
// subdir; add both when present. Capped so a project with a huge libdeps tree
// cannot blow up clangd's argv.
const MAX_DEP_DIRS = 120

/**
 * Find the include directories a C/C++ project expects to be on the search
 * path: the project's own headers (include/src/lib), and every installed
 * library under lib/ and .pio/libdeps (PlatformIO). Returns absolute paths.
 * Best-effort and bounded; a missing directory is simply skipped.
 */
export async function discoverIncludeDirs(root: string): Promise<{ project: string[]; deps: string[] }> {
  const project: string[] = []
  const deps: string[] = []
  const isDir = async (p: string): Promise<boolean> => {
    try {
      return (await stat(p)).isDirectory()
    } catch {
      return false
    }
  }
  const listDirs = async (p: string): Promise<string[]> => {
    try {
      const entries = await readdir(p, { withFileTypes: true })
      return entries.filter((e) => e.isDirectory()).map((e) => join(p, e.name))
    } catch {
      return []
    }
  }
  // Add a library dir and its src/ subdir; returns false once the cap is
  // reached so callers stop walking (bounding both the argv and the fs work).
  const addLib = async (dir: string): Promise<boolean> => {
    if (deps.length >= MAX_DEP_DIRS) return false
    deps.push(dir)
    const src = join(dir, 'src')
    if (deps.length < MAX_DEP_DIRS && (await isDir(src))) deps.push(src)
    return deps.length < MAX_DEP_DIRS
  }
  // The project's own headers.
  for (const d of ['include', 'src']) if (await isDir(join(root, d))) project.push(join(root, d))
  // PlatformIO installed dependencies first: these are the ones a user most
  // needs resolved, so a large local lib/ tree cannot starve them out of the cap.
  const libdeps = join(root, '.pio', 'libdeps')
  libdepsLoop: for (const env of await listDirs(libdeps)) {
    for (const lib of await listDirs(env)) {
      if (!(await addLib(lib))) break libdepsLoop
    }
  }
  // lib/<Name> and lib/<Name>/src (Arduino/PlatformIO local libraries).
  for (const libDir of await listDirs(join(root, 'lib'))) {
    if (!(await addLib(libDir))) break
  }
  return { project, deps }
}

/** Append `.clangd` to <root>/.gitignore (create/dedupe) so a machine-specific,
 * absolute-path config is never committed. Best-effort. */
async function ignoreClangd(root: string): Promise<void> {
  const path = join(root, '.gitignore')
  let text = ''
  try {
    text = await readFile(path, 'utf8')
  } catch {
    text = ''
  }
  const has = text.split(/\r?\n/).some((l) => l.trim() === '.clangd')
  if (has) return
  const next = (text && !text.endsWith('\n') ? text + '\n' : text) + '.clangd\n'
  try {
    await writeFile(path, next, 'utf8')
  } catch {
    /* read-only workspace: nothing we can do */
  }
}

/**
 * Ensure `<root>/.clangd` reflects the project's toolchain. No-op when the user
 * authored their own config, or when the compiler cannot be probed (clangd then
 * falls back to its built-in defaults rather than a broken half-config).
 */
export async function ensureClangdConfig(root: string): Promise<void> {
  const cfgPath = join(root, '.clangd')
  let existing: string | null = null
  try {
    let raw = await readFile(cfgPath, 'utf8')
    // Strip a leading BOM (code point U+FEFF): an editor that re-saves our file
    // with one would otherwise defeat the marker check below and strand a stale
    // config.
    if (raw.charCodeAt(0) === 0xfeff) raw = raw.slice(1)
    existing = raw
  } catch {
    existing = null
  }
  // Respect a hand-written config; only manage our own.
  if (existing !== null && !existing.startsWith(MARKER)) return

  const pc = await getProjectConfig(root).catch(() => ({}) as { compiler?: string; std?: string; cStd?: string })
  // The same normalization the build path applies. Reading the raw field here
  // meant a project pinning a CROSS compiler made clangd analyse with
  // --target=arm-none-eabi and newlib headers while every build used host g++,
  // so #ifdef-guarded code was analysed on a different branch than it compiled.
  const compiler = hostCppOrNull(pc.compiler) || 'g++'
  const cppStd = pc.std || 'c++23'
  // The project's C standard, so clangd flags the same C code the build does
  // rather than analysing every .c file as c17 regardless of the setting.
  const cStd = pc.cStd || 'c17'
  // getProjectConfig already drops a non-bare workspace compiler, but re-check
  // at the spawn site: only run an allowlisted, bare (PATH-resolved) driver, so
  // an untrusted config can never point the probe at an arbitrary binary.
  if (!isBareCommand(compiler) || !isAllowedCommand(compiler)) return
  const tc = await deriveToolchain(compiler)
  // Without real include paths the file adds nothing and could pin a wrong
  // target; leave clangd to its defaults instead.
  if (tc.includes.length === 0) return

  const { project, deps } = await discoverIncludeDirs(root)
  const content = buildClangdConfig(tc, cppStd, cStd, project, deps)
  if (existing === content) return
  try {
    await writeFile(cfgPath, content, 'utf8')
    await ignoreClangd(root)
  } catch {
    /* read-only workspace: skip silently, clangd still runs (degraded) */
  }
}
